version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    container_name: postgresdb
    ports: 
      - "5432:5432"

  backend:
    build: ./backend
    command: npm --prefix ./backend start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db